# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702f069caf5078a3ac851577be5c7f6b7e5ff6cd8c7a4e1a3addfdb464d4b109eb57c6d1f57a7fa233b605519dfb1cf0bbd1036045a35a4f9a07a240accc1a51

test:
  secret_key_base: d91102b8df704c3bb7d43bd8e310a2e0b3df07168c6a31861fee935cfe33b0f833565a82dabe61d39caea9c14646c26f9ccea7e40b8eea0353b6186e33c95cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
